### ISSUE TITLE
Jen blbost

### ISSUE THREAD

**Issue by JiriKursky** [bruxy70/CZ-Public-Transport#1]
Zdravím, jen malá chybka v readme.md "dod not" a nerozumím "without trains, and trains" trams? 
Jinak hraju si s komponentama někdy a od jara, takže začátečník.
Koukám i do svého kódu a mám tam stejnou zbytečnost "hass" je v entitě globální.
Chtělo by to kouknout ještě do const.py je tam CONF_WEEKDAY a asi i další.
Volání get asi nebude asynchronní - nevím jak je to tam s timeoutem. HA si může stěžovat, že mu něco bere prostředky.

**Comment by bruxy70** [comment]
Dik. Dokumentaci jsem opravil. Jizdni ABCz je bez vlaku, tramvaje tam jsou.
Na kod kouknu. Je to muj prvni komponent a dost dost v tom tapu.
Nejdrive jsem to mel jen jako REST sensor, ale s kazdou zmenou jizdniho radu se meni URL, takze jsem nakonec se nakonec zacal ucit Python :).
Co myslite tou zbytecnosti, ze hass je v entite globalni? Sorry, fakt zacinam (tak 2-3 tydny).
A tim getem taky nevim co jineho delat :( Snazim se obcas poptat a na Discordu, ale nejak se mi nedari.

**Comment by JiriKursky** [comment]
Koukni na moje https://github.com/JiriKursky/httas/blob/master/custom_components/httas/switch.py. Nahoře je import globálních proměnných z HA a proměnná hass je dosažiltelná v Entity self.hass bez nutnosti inicializace. Na řádku 137 je "get". Nejvtipnější na tom je, že nevím, jestli je to ok..:)), ale funguje. Někde je článek o "standardu" programování pro HA. Pokud na něj narazím pošlu. S Pythonem jsem čtyři měsíce napřed :))  a například z datetime přímo kvetu.  Klidně napiš na jiri.kursky@gmail.com.
