### ISSUE TITLE
Golemio API

### ISSUE THREAD

**Issue by rosiste** [bruxy70/CZ-Public-Transport#23]
Ahoj Vašku,
  integrace pro českou veřejnou dopravu, budu psát česky. Protože CHAPS nefunguje (a z podsataty asi nikdy nebude moc otevřený k tomu poskytovat něco zdarma - magistrát s tím dost bojuje, jak jsem četl) - nezkoušel jsi Golemio API? Jsou to otevřená data, která poskytuje město a jsou tam jízdní řády PID včetně vlaků a zpoždění.

**Comment by bruxy70** [comment]
Ahoj,
Dik za tip, o Golemio jsem nevedel a urcite na to kouknu.
Ta moje integrace zatim pouziva testovaci API od CHAPS, a zatim funguje dobre a spolehlive, vcetne zpozdeni. Ale je pravda, ze tam nejsou vlaky. Kouknu na to. Dik
Ahoj
V

**Comment by rosiste** [comment]
Open data Prahy najdes na http://opendata.praha.eu/
Konkrétní datové sady pro PID http://opendata.praha.eu/dataset?q=PID
Chce to vygenerovat API klíč, ale zřídili mi ho relativně rychle. Získání odjezdů z konkrétní zastávky je potom velice snadné viz https://golemioapi.docs.apiary.io/#reference/public-transport/departure-boards/get-departure-board

**Comment by bruxy70** [comment]
Dik.
Ta integrace by mela umet cely Cesko, ne jen Prahu. Ale je pravda, ze s tim demo uctem to umi jen Prahu.
Plus nehledam zastavkovy jizdni rad, ale spojeni (coz by idealne melo zjistit idealni spoj, vcetne vlaku - kterej opet ale v tom demo ucti neni - tak alespon to hleda mezi busy/tram/metro).
Kouknu na to. Na zastavkovy rad by mela jit pouzit standardni HA ingegrace GTFS, takz epokud by to fungovalo, muzu tuhle integraci zrusit...

**Comment by bruxy70** [comment]
Koukal jsem na to Golemio, a asi by to bylo dost omezeni funkcnosti toho, co ted funguje dobre.
Takze dokud to pojede, asi to necham tak jak to je. Urcite na to ale jde pouzit standardni REST API sensor.
